- model_params:
    lit_resnet:
      lr: 0.05
      max_epochs: 30
      num_classes: 10
      momentum: 0.9,
      weight_decay: 5e-4
      accelerator: "auto"
    swa_resnet:
      lr: 0.01
      name: SWAResnet
- exp_params:
    BATCH_SIZE: 256
    NUM_WORKERS: 4

